/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import connections.Conn;
import javax.swing.JOptionPane;
import user.client;

/**
 *
 * @author NCUNHA
 */
public class Client extends javax.swing.JFrame {

    
    
    
    
    Conn connection = new Conn();
       
    //Objectos
    client data = new client();
      
    //Atributos
    private final int botaoUmValor=1;
    private final int botaoCincoValor=5;
    private final int botaoDezValor=10;    
    private int totalAbastecer;
    
    private String energia;
    
    
    
    public void labelName(){
        //connection.connGetClientes("1705170005");
        //jlblClient.setText(connection.getNome());
    }
    
    
    
    
    
    /**
     * Creates new form Client
     */
    public Client() {

        initComponents();
        labelName();
    }       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblApp = new javax.swing.JLabel();
        jbttEncher = new javax.swing.JButton();
        jlblbotaoUm = new javax.swing.JButton();
        jlblbotaoCinco = new javax.swing.JButton();
        jlblbotaoDez = new javax.swing.JButton();
        jftxtfieldOutput = new javax.swing.JFormattedTextField();
        jbttLimpar = new javax.swing.JButton();
        jbttAbastecer = new javax.swing.JButton();
        jbttGasolina = new javax.swing.JButton();
        jbttGasoleo = new javax.swing.JButton();
        jbttElet = new javax.swing.JButton();
        jbttGas = new javax.swing.JButton();
        jlblClient = new javax.swing.JLabel();
        jbttPlasma = new javax.swing.JButton();
        jbttHidro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jlblApp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblApp.setText("BOFU");

        jbttEncher.setText("Encher");
        jbttEncher.setToolTipText("");

        jlblbotaoUm.setText("1€");
        jlblbotaoUm.setToolTipText("");
        jlblbotaoUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblbotaoUmActionPerformed(evt);
            }
        });

        jlblbotaoCinco.setText("5€");
        jlblbotaoCinco.setToolTipText("");
        jlblbotaoCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblbotaoCincoActionPerformed(evt);
            }
        });

        jlblbotaoDez.setText("10€");
        jlblbotaoDez.setToolTipText("");
        jlblbotaoDez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblbotaoDezActionPerformed(evt);
            }
        });

        jftxtfieldOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtfieldOutput.setToolTipText("");

        jbttLimpar.setText("Limpar");

        jbttAbastecer.setText("Abastecer");
        jbttAbastecer.setToolTipText("");
        jbttAbastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttAbastecerActionPerformed(evt);
            }
        });

        jbttGasolina.setText("Gasolina");
        jbttGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttGasolinaActionPerformed(evt);
            }
        });

        jbttGasoleo.setText("Gasóleo");
        jbttGasoleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttGasoleoActionPerformed(evt);
            }
        });

        jbttElet.setText("Eletricidade");
        jbttElet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttEletActionPerformed(evt);
            }
        });

        jbttGas.setText("Gás");

        jlblClient.setText("Nome");
        jlblClient.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jlblClientPropertyChange(evt);
            }
        });

        jbttPlasma.setText("Plasma");

        jbttHidro.setText("Hidrogeneo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblApp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jftxtfieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlblbotaoUm)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlblbotaoCinco)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbttElet)
                                            .addComponent(jlblbotaoDez)
                                            .addComponent(jbttGas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbttAbastecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbttLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbttEncher, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbttGasolina)
                                        .addGap(202, 202, 202)
                                        .addComponent(jbttPlasma, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbttGasoleo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbttHidro)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblApp)
                .addGap(18, 18, 18)
                .addComponent(jlblClient)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttElet)
                    .addComponent(jbttGasolina)
                    .addComponent(jbttPlasma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttGasoleo)
                    .addComponent(jbttGas)
                    .addComponent(jbttHidro))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblbotaoCinco)
                    .addComponent(jlblbotaoDez)
                    .addComponent(jlblbotaoUm)
                    .addComponent(jbttEncher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbttLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jbttAbastecer))
                    .addComponent(jftxtfieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jlblClient.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    private void jlblbotaoCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblbotaoCincoActionPerformed
         totalAbastecer +=botaoCincoValor;
        
         JOptionPane.showConfirmDialog(rootPane, totalAbastecer); 
    }//GEN-LAST:event_jlblbotaoCincoActionPerformed

    
    private void jlblbotaoUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblbotaoUmActionPerformed
     
         totalAbastecer +=botaoUmValor;
        
         JOptionPane.showConfirmDialog(rootPane, totalAbastecer);        
        
    }//GEN-LAST:event_jlblbotaoUmActionPerformed

    private void jbttGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbttGasolinaActionPerformed

    private void jbttGasoleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttGasoleoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbttGasoleoActionPerformed

    private void jbttEletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttEletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbttEletActionPerformed

    private void jlblClientPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jlblClientPropertyChange
        
    }//GEN-LAST:event_jlblClientPropertyChange

    private void jlblbotaoDezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblbotaoDezActionPerformed
        totalAbastecer +=botaoDezValor;
        
         JOptionPane.showConfirmDialog(rootPane, totalAbastecer);
    }//GEN-LAST:event_jlblbotaoDezActionPerformed

    private void jbttAbastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttAbastecerActionPerformed
          
        data.getGuiCliente(totalAbastecer, energia);
        jlblClient.setText(connection.getNome());
        JOptionPane.showConfirmDialog(rootPane, connection.getFatura());
    }//GEN-LAST:event_jbttAbastecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbttAbastecer;
    private javax.swing.JButton jbttElet;
    private javax.swing.JButton jbttEncher;
    private javax.swing.JButton jbttGas;
    private javax.swing.JButton jbttGasoleo;
    private javax.swing.JButton jbttGasolina;
    private javax.swing.JButton jbttHidro;
    private javax.swing.JButton jbttLimpar;
    private javax.swing.JButton jbttPlasma;
    private javax.swing.JFormattedTextField jftxtfieldOutput;
    private javax.swing.JLabel jlblApp;
    private javax.swing.JLabel jlblClient;
    private javax.swing.JButton jlblbotaoCinco;
    private javax.swing.JButton jlblbotaoDez;
    private javax.swing.JButton jlblbotaoUm;
    // End of variables declaration//GEN-END:variables
}
